# Generated by Django 5.2.4 on 2025-07-12 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing_images/')),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('other', 'Other')], max_length=20)),
                ('type', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('worn_out', 'Worn Out')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('swapped', 'Swapped'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
